/*
 * Copyright © 2017-2019 Cask Data, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package io.cdap.wrangler.api.parser;

import io.cdap.wrangler.api.annotations.PublicEvolving;

/**
 * The class <code>SyntaxError</code> contains information about the errors observed
 * during parsing of the recipe.
 *
 * <p>It contains the line number, character position, the error message, and the
 * source line that has errors.</p>
 */
@PublicEvolving
public final class SyntaxError {
    /**
     * The line number where the syntax error occurred.
     */
    private final int lineNo;

    /**
     * The character position within the line where the error is suspected.
     */
    private final int charPos;

    /**
     * The error message generated by the parser for the line.
     */
    private final String message;

    /**
     * The original line that has the syntax error.
     */
    private final String line;

    /**
     * Constructs a new <code>SyntaxError</code> object.
     *
     * @param lineNo  The line number where the syntax error occurred.
     * @param charPos The character position within the line where the error is suspected.
     * @param message The error message generated by the parser for the line.
     * @param line    The original line that has the syntax error.
     */
    public SyntaxError(final int lineNo, final int charPos, final String message, final String line) {
        this.lineNo = lineNo;
        this.charPos = charPos;
        this.message = message;
        this.line = line;
    }

    /**
     * Returns the line number where the syntax error occurred.
     *
     * @return The line number where the syntax error occurred.
     */
    public final int getLineNumber() {
        return lineNo;
    }

    /**
     * Returns the character position within the line where the error is suspected.
     *
     * @return The character position within the line where the error is suspected.
     */
    public final int getCharPosition() {
        return charPos;
    }

    /**
     * Returns the error message generated by the parser for the line.
     *
     * @return The error message generated by the parser for the line.
     */
    public final String getMessage() {
        return message;
    }

    /**
     * Returns the original line that has the syntax error.
     *
     * @return The original line that has the syntax error.
     */
    public final String getLine() {
        return line;
    }

    /**
     * Returns the string representation of this <code>SyntaxError</code> object.
     *
     * @return The string representation of this object.
     */
    @Override
    public final String toString() {
        return message;
    }
}
